version: "2"
services:
  nodeserver:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    command: mongod --port 27018
    ports:
      - "27018:27018"


